export const DEMO_RESULTS = [
  {
    businessName: "Atlas Metrics",
    website: "https://example.com/atlas-metrics",
    username: "atlasmetrics",
    profileUrl: "https://flourisher.net/atlasmetrics",
    stripeIntegration: "Marketplace app: analytics",
    acceptsLink: true,
    projects: true,
    projectUrl: "https://flourisher.net/projects/atlasmetrics",
    verified: "Gold",
    products: "Cohort dashboards; KPI alerts",
    users: "Growth teams; SaaS founders",
  },
  {
    businessName: "Northstar Loop",
    website: "https://example.com/northstar-loop",
    username: "northstar",
    profileUrl: "https://flourisher.net/northstar",
    stripeIntegration: "Embedded Connect partner",
    acceptsLink: true,
    projects: true,
    projectUrl: "https://flourisher.net/projects/northstar",
    verified: "Silver",
    products: "Creator payouts; usage billing",
    users: "Marketplaces; agencies",
  },
  {
    businessName: "Ledgerfield",
    website: "https://example.com/ledgerfield",
    username: "ledgerfield",
    profileUrl: "https://flourisher.net/ledgerfield",
    stripeIntegration: "Verified extension",
    acceptsLink: false,
    projects: false,
    projectUrl: null,
    verified: "Gold",
    products: "Revenue recognition; exports",
    users: "Finance operators; controllers",
  },
  {
    businessName: "BrightCart",
    website: "https://example.com/brightcart",
    username: "brightcart",
    profileUrl: "https://flourisher.net/brightcart",
    stripeIntegration: "Checkout plugin",
    acceptsLink: true,
    projects: true,
    projectUrl: "https://flourisher.net/projects/brightcart",
    verified: "Community",
    products: "Digital storefronts; bundles",
    users: "Solo sellers; newsletter shops",
  },
  {
    businessName: "Signal Orchard",
    website: "https://example.com/signal-orchard",
    username: "signalorchard",
    profileUrl: "https://flourisher.net/signalorchard",
    stripeIntegration: "Marketplace app: reporting",
    acceptsLink: true,
    projects: false,
    projectUrl: null,
    verified: "Silver",
    products: "MRR trend reports; scorecards",
    users: "RevOps; investors",
  },
  {
    businessName: "Harbor Grid",
    website: "https://example.com/harbor-grid",
    username: "harborgrid",
    profileUrl: "https://flourisher.net/harborgrid",
    stripeIntegration: "Custom integration",
    acceptsLink: false,
    projects: true,
    projectUrl: "https://flourisher.net/projects/harborgrid",
    verified: "Pilot",
    products: "Procurement workflows; approvals",
    users: "Operations teams; B2B buyers",
  },
  {
    businessName: "PulseFoundry",
    website: "https://example.com/pulsefoundry",
    username: "pulsefoundry",
    profileUrl: "https://flourisher.net/pulsefoundry",
    stripeIntegration: "Billing portal add-on",
    acceptsLink: true,
    projects: true,
    projectUrl: "https://flourisher.net/projects/pulsefoundry",
    verified: "Gold",
    products: "Customer health; renewal nudges",
    users: "Customer success; founders",
  },
  {
    businessName: "Kiteplane",
    website: "https://example.com/kiteplane",
    username: "kiteplane",
    profileUrl: "https://flourisher.net/kiteplane",
    stripeIntegration: "No public listing",
    acceptsLink: true,
    projects: false,
    projectUrl: null,
    verified: "Unverified",
    products: "Usage metering; entitlement sync",
    users: "API companies; platform teams",
  },
  {
    businessName: "Mosaic Ledger",
    website: "https://example.com/mosaic-ledger",
    username: "mosaicledger",
    profileUrl: "https://flourisher.net/mosaicledger",
    stripeIntegration: "Marketplace app: finance",
    acceptsLink: true,
    projects: true,
    projectUrl: "https://flourisher.net/projects/mosaicledger",
    verified: "Gold",
    products: "Close automation; anomaly review",
    users: "Bookkeepers; fractional CFOs",
  },
  {
    businessName: "Launchlane",
    website: "https://example.com/launchlane",
    username: "launchlane",
    profileUrl: "https://flourisher.net/launchlane",
    stripeIntegration: "Payment Links specialist",
    acceptsLink: true,
    projects: false,
    projectUrl: null,
    verified: "Community",
    products: "Landing pages; preorders",
    users: "Indie makers; course creators",
  },
  {
    businessName: "Copper Canary",
    website: "https://example.com/copper-canary",
    username: "coppercanary",
    profileUrl: "https://flourisher.net/coppercanary",
    stripeIntegration: "Radar companion",
    acceptsLink: false,
    projects: true,
    projectUrl: "https://flourisher.net/projects/coppercanary",
    verified: "Silver",
    products: "Fraud review queues; alerts",
    users: "Risk teams; support leads",
  },
  {
    businessName: "Ribbon Desk",
    website: "https://example.com/ribbon-desk",
    username: "ribbondesk",
    profileUrl: "https://flourisher.net/ribbondesk",
    stripeIntegration: "Support app integration",
    acceptsLink: true,
    projects: true,
    projectUrl: "https://flourisher.net/projects/ribbondesk",
    verified: "Pilot",
    products: "Refund workflows; customer notes",
    users: "Support teams; ecommerce ops",
  },
  {
    businessName: "Summit Schema",
    website: "https://example.com/summit-schema",
    username: "summitschema",
    profileUrl: "https://flourisher.net/summitschema",
    stripeIntegration: "Data pipeline partner",
    acceptsLink: true,
    projects: false,
    projectUrl: null,
    verified: "Gold",
    products: "Warehouse sync; dbt models",
    users: "Data teams; analytics engineers",
  },
  {
    businessName: "Fieldnote Pay",
    website: "https://example.com/fieldnote-pay",
    username: "fieldnotepay",
    profileUrl: "https://flourisher.net/fieldnotepay",
    stripeIntegration: "Terminal services partner",
    acceptsLink: false,
    projects: true,
    projectUrl: "https://flourisher.net/projects/fieldnotepay",
    verified: "Silver",
    products: "In-person checkout; receipts",
    users: "Studios; event operators",
  },
  {
    businessName: "Beacon Basket",
    website: "https://example.com/beacon-basket",
    username: "beaconbasket",
    profileUrl: "https://flourisher.net/beaconbasket",
    stripeIntegration: "Checkout plugin",
    acceptsLink: true,
    projects: false,
    projectUrl: null,
    verified: "Community",
    products: "Gift cards; cart recovery",
    users: "Retailers; membership clubs",
  },
  {
    businessName: "Quota Studio",
    website: "https://example.com/quota-studio",
    username: "quotastudio",
    profileUrl: "https://flourisher.net/quotastudio",
    stripeIntegration: "Subscription toolkit",
    acceptsLink: true,
    projects: true,
    projectUrl: "https://flourisher.net/projects/quotastudio",
    verified: "Gold",
    products: "Plans; trials; cancellation flows",
    users: "B2B SaaS; product teams",
  },
  {
    businessName: "Fairwater Labs",
    website: "https://example.com/fairwater-labs",
    username: "fairwater",
    profileUrl: "https://flourisher.net/fairwater",
    stripeIntegration: "Custom integration",
    acceptsLink: false,
    projects: false,
    projectUrl: null,
    verified: "Pilot",
    products: "Pricing experiments; surveys",
    users: "Product marketers; founders",
  },
  {
    businessName: "Vector Grove",
    website: "https://example.com/vector-grove",
    username: "vectorgrove",
    profileUrl: "https://flourisher.net/vectorgrove",
    stripeIntegration: "Marketplace app: analytics",
    acceptsLink: true,
    projects: true,
    projectUrl: "https://flourisher.net/projects/vectorgrove",
    verified: "Silver",
    products: "Segment analysis; lead scoring",
    users: "Sales teams; growth analysts",
  },
];

export const RESULT_FIELDS = [
  "businessName",
  "website",
  "username",
  "profileUrl",
  "stripeIntegration",
  "acceptsLink",
  "projects",
  "projectUrl",
  "verified",
  "products",
  "users",
];
